### ISSUE TITLE
[Fumo Request] Saber from fate/stay night

### ISSUE THREAD

**Issue by rautyrauty** [upsidedownsweetfood/FumoPlushiesMT#2]
It's vital for me.
![изображение](https://github.com/upsidedownsweetfood/FumoPlushiesMT/assets/108220148/18667b2e-f8a1-4daa-8051-369201d274a3)

**Comment by upsidedownsweetfood** [comment]
Alright, I'll try to make her up quickly

**Comment by rautyrauty** [comment]
I wanted to try to make this model myself and saw that you are using blockbench. Are there really no better projects than blockbench written in js? 🤮

**Comment by upsidedownsweetfood** [comment]
> I wanted to try to make this model myself and saw that you are using blockbench. Are there really no better projects than blockbench written in js? 🤮

Well, uh, I know how to use blender too, I just used the right tool for the job when I started the mod.

I'm fine with moving everything to blender.

**Comment by ghost** [comment]
Not a Blender User, but I see, when I go into the Model folder, that the Models are OBJ files.

Is it possible with Blender to save as OBJ, without Add-ons/Plug-ins?

Just a thought I have, after I saw, that here are few more comments than before.

**Comment by upsidedownsweetfood** [comment]
yep! you can
